#!/bin/bash
# Generated by setup-quality.sh v1.0.0
# To upgrade: Re-run setup script in this project
#
# SAFE WORD Claude Config - SessionStart Hook
# Injects version and status into Claude's context (silent - not displayed to user)

echo "SAFE WORD Claude Config v1.0.0 installed - auto-linting and quality review active"

exit 0
