#!/bin/bash
################################################################################
# Claude Code Linting Hook Setup Script
#
# This script configures ESLint and Prettier to run automatically when Claude
# Code makes changes to your project files.
#
# Usage:
#   bash setup-linting.sh              # TypeScript mode (default)
#   bash setup-linting.sh --minimal    # Minimal (JS only)
#   bash setup-linting.sh --react      # React + TypeScript
#   bash setup-linting.sh --electron   # Electron + TypeScript
#   bash setup-linting.sh --astro      # Astro + TypeScript
#   bash setup-linting.sh --biome      # Biome (linter + formatter combined)
#
# Modes:
#   --minimal   : ESLint + Prettier (~10MB)
#   (default)   : + TypeScript (~25MB)
#   --react     : + React + Hooks (~35MB)
#   --electron  : Same as TypeScript (~25MB)
#   --astro     : + Astro plugin (~30MB)
#   --biome     : Biome only (~15MB, 10-25x faster)
#
# Configuration:
# - Auto-fix: Enabled by default (--fix, --write)
# - Blocking: Non-blocking by default (shows warnings, doesn't stop Claude)
# - Scope: Only lints changed files (faster, more targeted)
################################################################################

set -e  # Exit on error

VERSION="v1.0.0"

# Version header for generated files
VERSION_HEADER="# Generated by setup-linting.sh $VERSION
# To upgrade: Re-run setup script in this project
#"

# Parse mode argument
MODE="${1:-typescript}"
case "$MODE" in
  --minimal)
    MODE="minimal"
    ;;
  --typescript|--ts)
    MODE="typescript"
    ;;
  --react)
    MODE="react"
    ;;
  --electron)
    MODE="electron"
    ;;
  --astro)
    MODE="astro"
    ;;
  --biome)
    MODE="biome"
    ;;
  *)
    MODE="typescript"  # Default
    ;;
esac

echo "================================="
echo "Claude Code Linting Setup"
echo "Mode: $MODE"
echo "================================="
echo ""

# Check if we're in a directory where we can write
if [ ! -w "." ]; then
  echo "ERROR: Cannot write to current directory. Please cd to your project root."
  exit 1
fi

PROJECT_ROOT="$(pwd)"
echo "Setting up linting in: $PROJECT_ROOT"
echo ""

# ============================================================================
# Step 1: Initialize package.json if needed
# ============================================================================
echo "[1/6] Checking for package.json..."

if [ ! -f "package.json" ]; then
  echo "  No package.json found. Creating one..."
  cat > package.json << 'EOF'
{
  "name": "my-project",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "scripts": {},
  "devDependencies": {}
}
EOF
  echo "  ✓ Created package.json"
else
  echo "  ✓ package.json exists"
fi
echo ""

# ============================================================================
# Step 2: Check dependencies
# ============================================================================
echo "[2/6] Checking dependencies..."

# Check if npm is available
if ! command -v npm &> /dev/null; then
  echo "ERROR: npm is not installed. Please install Node.js and npm first."
  exit 1
fi

# Check if jq is available (required for hooks)
if ! command -v jq &> /dev/null; then
  echo "WARNING: jq is not installed. Claude Code hooks require jq."
  echo "  Install it:"
  echo "    • macOS: brew install jq"
  echo "    • Ubuntu/Debian: sudo apt-get install jq"
  echo "    • Other: https://jqlang.github.io/jq/download/"
  echo ""
  echo "  Continuing anyway (hooks will fail without jq)..."
fi

echo "  ✓ Dependencies checked"
echo ""

# ============================================================================
# Step 3: Install linters
# ============================================================================

# Check if packages are already installed
SKIP_INSTALL=false

if [ "$MODE" = "biome" ]; then
  echo "[3/6] Checking for Biome..."
  PACKAGES="@biomejs/biome"

  # Check if Biome is already installed
  if grep -q '"@biomejs/biome"' package.json 2>/dev/null; then
    echo "  ✓ Biome already installed (skipping npm install)"
    SKIP_INSTALL=true
  else
    echo "  Installing Biome..."
  fi
else
  echo "[3/6] Installing ESLint and Prettier..."
  # Determine packages based on mode
  # Tier 1 only: Fast, objective, immediate feedback (no SonarJS, no a11y, no security)
  BASE_PACKAGES="eslint @eslint/js prettier eslint-config-prettier globals"

  case "$MODE" in
    minimal)
      PACKAGES="$BASE_PACKAGES"
      ;;
    typescript)
      PACKAGES="$BASE_PACKAGES typescript-eslint"
      ;;
    react)
      PACKAGES="$BASE_PACKAGES typescript-eslint @eslint-react/eslint-plugin eslint-plugin-react-hooks"
      ;;
    electron)
      PACKAGES="$BASE_PACKAGES typescript-eslint"
      ;;
    astro)
      PACKAGES="$BASE_PACKAGES typescript-eslint eslint-plugin-astro"
      ;;
  esac
fi

# Install linters as dev dependencies (unless already installed)
if [ "$SKIP_INSTALL" = false ]; then
  echo "  Installing packages (this may take a moment)..."
  echo "  Packages: $PACKAGES"
  npm install --save-dev $PACKAGES --silent 2>&1 | grep -v "npm WARN" || true
  echo "  ✓ Installed packages for $MODE mode"
else
  echo "  ✓ Using existing packages"
fi
echo ""

# ============================================================================
# Step 4: Add npm scripts for manual linting
# ============================================================================
echo "[4/6] Adding npm scripts..."

# Use a simple approach: read, modify with jq, write back
if command -v jq &> /dev/null; then
  # Add scripts using jq
  if [ "$MODE" = "biome" ]; then
    jq '.scripts.lint = "biome check ." | .scripts.format = "biome check --write ."' package.json > package.json.tmp
    mv package.json.tmp package.json
    echo "  ✓ Added 'npm run lint' and 'npm run format' scripts (Biome)"
  else
    jq '.scripts.lint = "eslint ." | .scripts.format = "prettier --write ."' package.json > package.json.tmp
    mv package.json.tmp package.json
    echo "  ✓ Added 'npm run lint' and 'npm run format' scripts"
  fi
else
  echo "  ⚠ jq not found - please manually add these scripts to package.json:"
  if [ "$MODE" = "biome" ]; then
    echo '    "lint": "biome check ."'
    echo '    "format": "biome check --write ."'
  else
    echo '    "lint": "eslint ."'
    echo '    "format": "prettier --write ."'
  fi
fi
echo ""

# ============================================================================
# Step 5: Create .claude directory and settings.json
# ============================================================================
echo "[5/6] Configuring Claude Code hooks..."

mkdir -p .claude/hooks

# Create shared linting script (core logic)
if [ "$MODE" = "biome" ]; then
  {
    echo '#!/bin/bash'
    echo "$VERSION_HEADER"
    cat << 'EOF'
################################################################################
# Shared Linting Script (Biome)
#
# Runs Biome linter + formatter on files passed as arguments.
# Used by both PostToolUse hooks and manual /lint command.
#
# Usage:
#   run-linters.sh file1.js file2.ts    # Lint specific files
#   run-linters.sh .                    # Lint all files in project
#
# Environment variables:
#   CLAUDE_PROJECT_DIR - Project root (defaults to current directory)
################################################################################

# Change to project directory if specified
if [ -n "$CLAUDE_PROJECT_DIR" ]; then
  cd "$CLAUDE_PROJECT_DIR" || exit 1
fi

# Check if npx is available (once, before the loop)
if ! command -v npx >/dev/null 2>&1; then
  echo "Error: npx not found. Please install Node.js and npm." >&2
  exit 1
fi

# Process each file/directory argument
for target in "$@"; do
  # Skip if target doesn't exist
  if [ ! -e "$target" ]; then
    echo "Warning: $target does not exist, skipping" >&2
    continue
  fi

  # Run Biome (linting + formatting combined)
  echo "Linting & formatting: $target"
  npx biome check --write "$target" 2>&1 || true
done
EOF
  } > .claude/hooks/run-linters.sh
else
  {
    echo '#!/bin/bash'
    echo "$VERSION_HEADER"
    cat << 'EOF'
################################################################################
# Shared Linting Script
#
# Runs Prettier and ESLint on files passed as arguments.
# Used by both PostToolUse hooks and manual /lint command.
#
# Usage:
#   run-linters.sh file1.js file2.ts    # Lint specific files
#   run-linters.sh .                    # Lint all files in project
#
# Environment variables:
#   CLAUDE_PROJECT_DIR - Project root (defaults to current directory)
################################################################################

# Change to project directory if specified
if [ -n "$CLAUDE_PROJECT_DIR" ]; then
  cd "$CLAUDE_PROJECT_DIR" || exit 1
fi

# Check if npx is available (once, before the loop)
if ! command -v npx >/dev/null 2>&1; then
  echo "Error: npx not found. Please install Node.js and npm." >&2
  exit 1
fi

# Process each file/directory argument
for target in "$@"; do
  # Skip if target doesn't exist
  if [ ! -e "$target" ]; then
    echo "Warning: $target does not exist, skipping" >&2
    continue
  fi

  # Run Prettier (formatting)
  echo "Formatting: $target"
  npx prettier --write "$target" 2>&1 || true

  # Run ESLint (linting)
  echo "Linting: $target"
  npx eslint --fix "$target" 2>&1 || true
done
EOF
  } > .claude/hooks/run-linters.sh
fi

chmod +x .claude/hooks/run-linters.sh

# Create PostToolUse hook wrapper for auto-linting
{
  echo '#!/bin/bash'
  echo "$VERSION_HEADER"
  cat << 'EOF'
################################################################################
# Auto-Lint PostToolUse Hook
#
# Automatically runs linters on files after Write/Edit/MultiEdit/NotebookEdit operations.
# Receives JSON via stdin containing tool_input.file_path or tool_input.notebook_path.
#
# This is a thin wrapper that extracts the file path from stdin and
# delegates to the shared run-linters.sh script.
################################################################################

# Read JSON from stdin (official Claude Code pattern)
input=$(cat)

# Extract file path from JSON
# Try file_path first (Write/Edit), fall back to notebook_path (NotebookEdit)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')

# Only proceed if we have a valid file path
if [ -n "$file_path" ] && [ -f "$file_path" ]; then
  # Call shared linting script
  "$CLAUDE_PROJECT_DIR/.claude/hooks/run-linters.sh" "$file_path"
fi

# Always exit 0 (non-blocking)
exit 0
EOF
} > .claude/hooks/auto-lint.sh

chmod +x .claude/hooks/auto-lint.sh

# Create lint slash command
mkdir -p .claude/commands

cat > .claude/commands/lint.md << 'EOF'
Run linting on all project files.

Execute:
```bash
bash .claude/hooks/run-linters.sh .
```

This runs both Prettier (formatting) and ESLint (linting) on all project files.
EOF

echo "  ✓ Created lint slash command"

# Create or update settings.json with linting hooks
if [ ! -f .claude/settings.json ]; then
  echo '{"hooks": {}}' > .claude/settings.json
  echo "  ✓ Created .claude/settings.json"
fi

# Check if auto-lint hook already exists in PostToolUse
if jq -e '.hooks.PostToolUse[]?.hooks[]? | select(.command == "$CLAUDE_PROJECT_DIR/.claude/hooks/auto-lint.sh")' .claude/settings.json > /dev/null 2>&1; then
  echo "  ✓ PostToolUse hook already exists (skipped)"
else
  # Append to PostToolUse array (or create if doesn't exist)
  jq '.hooks.PostToolUse = (.hooks.PostToolUse // []) + [{"matcher": "Write|Edit|MultiEdit|NotebookEdit", "hooks": [{"type": "command", "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/auto-lint.sh", "timeout": 15}]}]' \
    .claude/settings.json > .claude/settings.json.tmp
  mv .claude/settings.json.tmp .claude/settings.json
  echo "  ✓ Added PostToolUse hook to .claude/settings.json"
fi
echo "  ✓ Created .claude/hooks/run-linters.sh (shared linting logic)"
echo "  ✓ Created .claude/hooks/auto-lint.sh (PostToolUse hook wrapper)"
echo "  ✓ Created .claude/settings.json with linting hooks"
echo ""

# ============================================================================
# Step 6: Create basic config files if they don't exist
# ============================================================================
echo "[6/6] Checking for linter config files..."

# Biome mode: Create biome.jsonc
if [ "$MODE" = "biome" ]; then
  if [ ! -f "biome.json" ] && [ ! -f "biome.jsonc" ]; then
    cat > biome.jsonc << 'EOF'
{
  "$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true
  },
  "files": {
    "ignoreUnknown": false,
    "ignore": [
      "node_modules/",
      "dist/",
      "build/",
      ".next/",
      "coverage/",
      "*.min.js",
      "package-lock.json",
      "yarn.lock",
      "pnpm-lock.yaml"
    ]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "trailingCommas": "es5",
      "semicolons": "always"
    }
  }
}
EOF
    echo "  ✓ Created biome.jsonc (Biome configuration)"
  else
    echo "  ✓ biome.jsonc or biome.json already exists"
  fi

# ESLint modes: Create eslint.config.mjs
elif [ ! -f ".eslintrc.json" ] && [ ! -f ".eslintrc.js" ] && [ ! -f "eslint.config.js" ] && [ ! -f "eslint.config.mjs" ]; then

  case "$MODE" in
    minimal)
      cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/', '**/dist/', '**/build/', '**/.next/', '**/coverage/',
    '**/*.min.js', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml'
  ]),
  {
    name: 'base-config',
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2025 }
    }
  },
  { name: 'prettier-config', extends: [prettier] }
]);
EOF
      ;;

    typescript)
      cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/', '**/dist/', '**/build/', '**/.next/', '**/coverage/',
    '**/*.min.js', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml'
  ]),
  {
    name: 'base-config',
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2025 }
    }
  },
  {
    name: 'typescript-config',
    files: ['**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended]
  },
  { name: 'prettier-config', extends: [prettier] }
]);
EOF
      ;;

    react)
      cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from '@eslint-react/eslint-plugin';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/', '**/dist/', '**/build/', '**/.next/', '**/coverage/',
    '**/*.min.js', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml'
  ]),
  {
    name: 'base-config',
    files: ['**/*.{js,mjs,cjs,ts,tsx,jsx}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2025 },
      parserOptions: { ecmaFeatures: { jsx: true } }
    }
  },
  {
    name: 'typescript-config',
    files: ['**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended]
  },
  {
    name: 'react-config',
    files: ['**/*.{jsx,tsx}'],
    extends: [reactPlugin.configs['recommended-typescript']],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules
    }
  },
  { name: 'prettier-config', extends: [prettier] }
]);
EOF
      ;;

    electron)
      cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/', '**/dist/', '**/build/', '**/.next/', '**/coverage/',
    '**/*.min.js', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml'
  ]),
  {
    name: 'base-config',
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2025 }
    }
  },
  {
    name: 'typescript-config',
    files: ['**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended]
  },
  { name: 'prettier-config', extends: [prettier] }
]);
EOF
      ;;

    astro)
      cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import astroPlugin from 'eslint-plugin-astro';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig([
  globalIgnores([
    '**/node_modules/', '**/dist/', '**/build/', '**/.next/', '**/coverage/',
    '**/*.min.js', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml'
  ]),
  {
    name: 'base-config',
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2025 }
    }
  },
  {
    name: 'typescript-config',
    files: ['**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended]
  },
  ...astroPlugin.configs.recommended,
  { name: 'prettier-config', extends: [prettier] }
]);
EOF
      ;;
  esac

  echo "  ✓ Created eslint.config.mjs ($MODE mode)"
else
  echo "  ✓ ESLint config already exists"
fi

# Create Prettier config files (skip for biome mode)
if [ "$MODE" != "biome" ]; then
  # Create modern .prettierrc (Prettier 3.x best practices, 2025)
  if [ ! -f ".prettierrc" ] && [ ! -f ".prettierrc.json" ] && [ ! -f "prettier.config.js" ]; then
    cat > .prettierrc << 'EOF'
{
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "trailingComma": "all",
  "bracketSpacing": true,
  "bracketSameLine": false,
  "arrowParens": "avoid",
  "endOfLine": "lf"
}
EOF
    echo "  ✓ Created .prettierrc (Prettier 3.x modern defaults)"
  else
    echo "  ✓ Prettier config already exists"
  fi

  # Create .prettierignore if it doesn't exist
  if [ ! -f ".prettierignore" ]; then
    cat > .prettierignore << 'EOF'
node_modules
dist
build
.next
coverage
*.min.js
package-lock.json
EOF
    echo "  ✓ Created .prettierignore"
  else
    echo "  ✓ .prettierignore already exists"
  fi
fi

echo ""
echo "================================="
echo "✓ Setup Complete! ($MODE mode)"
echo "================================="
echo ""

# Mode-specific info
case "$MODE" in
  minimal)
    echo "Configured for: JavaScript (minimal)"
    echo "  • ESLint core rules + Prettier"
    ;;
  typescript)
    echo "Configured for: JavaScript + TypeScript"
    echo "  • Type checking enabled"
    ;;
  react)
    echo "Configured for: React + TypeScript"
    echo "  • React Hooks rules enabled (catches dependency bugs)"
    echo "  • React-specific patterns enforced"
    ;;
  electron)
    echo "Configured for: Electron + TypeScript"
    echo "  • Same as TypeScript mode (ES + TS + Prettier)"
    ;;
  astro)
    echo "Configured for: Astro + TypeScript"
    echo "  • Astro component (.astro files) linting enabled"
    ;;
  biome)
    echo "Configured for: Biome (linter + formatter combined)"
    echo "  • 10-25x faster than ESLint + Prettier"
    echo "  • TypeScript, JavaScript, JSX, TSX, JSON, CSS support"
    echo "  • Single tool for both linting and formatting"
    ;;
esac

echo ""
echo "What was configured:"
if [ "$MODE" = "biome" ]; then
  echo "  • Biome installed as dev dependency"
  echo "  • npm scripts added: 'npm run lint' and 'npm run format'"
  echo "  • Claude Code hooks configured to auto-lint on Write/Edit/NotebookEdit"
else
  echo "  • ESLint and Prettier installed as dev dependencies"
  echo "  • npm scripts added: 'npm run lint' and 'npm run format'"
  echo "  • Claude Code hooks configured to auto-lint on Write/Edit/NotebookEdit"
fi
echo ""
echo "Hook behavior:"
echo "  • Triggers on: Write, Edit, MultiEdit, and NotebookEdit tools ONLY"
echo "  • Auto-fix enabled: Code is automatically formatted and fixed"
echo "  • Non-blocking: Linting errors won't stop Claude (warns only)"
echo "  • File-scoped: Only changed files are linted (fast)"
echo ""
echo "To customize:"
if [ "$MODE" = "biome" ]; then
  echo "  • Edit biome.jsonc for linting and formatting rules"
  echo "  • Edit .claude/settings.json for hook behavior"
else
  echo "  • Edit eslint.config.mjs for ESLint rules"
  echo "  • Edit .prettierrc for Prettier formatting"
  echo "  • Edit .claude/settings.json for hook behavior"
fi
echo ""





