/**
 * Rust language pack file definitions
 *
 * Defines config generators and file definitions for:
 * - clippy.toml (lint thresholds)
 * - rustfmt.toml (formatting options)
 */

import type { FileDefinition, ManagedFileDefinition } from '../types.js';

// ============================================================================
// Config Generators
// ============================================================================

function generateClippyConfig(): string {
  return `# Generated by safeword - DO NOT EDIT
# Configure lint levels in Cargo.toml [lints.clippy] section

# Complexity constraints (match ESLint/ruff philosophy)
cognitive-complexity-threshold = 10
too-many-arguments-threshold = 5

# Stricter thresholds for LLM code
too-many-lines-threshold = 100
type-complexity-threshold = 250
`;
}

function generateRustfmtConfig(): string {
  return `# Generated by safeword - DO NOT EDIT
# Uses only stable options (works on all Rust toolchains)

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
use_field_init_shorthand = true
`;
}

// ============================================================================
// Owned Files (.safeword/ - overwritten on upgrade)
// ============================================================================

export const rustOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/clippy.toml': {
    generator: ctx => (ctx.languages?.rust ? generateClippyConfig() : undefined),
  },
  '.safeword/rustfmt.toml': {
    generator: ctx => (ctx.languages?.rust ? generateRustfmtConfig() : undefined),
  },
};

// ============================================================================
// Managed Files (project root - create if missing)
// ============================================================================

export const rustManagedFiles: Record<string, ManagedFileDefinition> = {
  'clippy.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingClippyConfig
        ? generateClippyConfig()
        : undefined,
  },
  'rustfmt.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingRustfmtConfig
        ? generateRustfmtConfig()
        : undefined,
  },
};
