/**
 * Go-specific Setup Utilities
 *
 * Handles Go tooling configuration during safeword setup:
 * - golangci-lint config (.golangci.yml)
 * - Layer detection for depguard import rules (future)
 */

import nodePath from 'node:path';

import { exists, writeFile } from '../../utils/fs.js';
import type { SetupResult } from '../types.js';

/**
 * Generate golangci-lint v2 configuration.
 *
 * Uses standard linter set with additional quality linters enabled.
 * Includes gofumpt formatter for stricter formatting.
 */
export function generateGolangciConfig(): string {
  return `# Generated by safeword
version: "2"

linters:
  default: standard
  enable:
    - gocritic       # Opinionated checks
    - gosec          # Security scanner
    - misspell       # Spelling mistakes
    - unconvert      # Unnecessary type conversions
    - unparam        # Unused function parameters
  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

formatters:
  enable:
    - gofumpt        # Stricter gofmt
`;
}

/**
 * Set up Go tooling configuration.
 *
 * Creates .golangci.yml if it doesn't exist.
 * Respects existing configuration (won't overwrite).
 *
 * @param cwd - Project root directory
 * @returns Result with created files
 */
export function setupGoTooling(cwd: string): SetupResult {
  const result: SetupResult = { files: [] };

  const configPath = nodePath.join(cwd, '.golangci.yml');

  // Skip if config already exists (don't clobber)
  if (exists(configPath)) {
    return result;
  }

  // Generate golangci-lint config
  const config = generateGolangciConfig();
  writeFile(configPath, config);
  result.files.push('.golangci.yml');

  return result;
}
