/**
 * Go-specific Setup Utilities
 *
 * Handles Go tooling configuration during safeword setup:
 * - golangci-lint config (.golangci.yml)
 * - Layer detection for depguard import rules (future)
 */

import nodePath from 'node:path';

import { exists, writeFile } from '../../utils/fs.js';
import type { SetupResult } from '../types.js';

/**
 * Generate golangci-lint v2 configuration.
 *
 * Uses ALL linters for maximum strictness, matching our philosophy
 * for TypeScript (ESLint) and Python (ruff).
 *
 * Design constraints (matching ESLint):
 * - cyclop: max-complexity 10 (default)
 * - nestif: max nesting 4
 * - funlen: max lines 60, statements 40
 */
export function generateGolangciConfig(): string {
  return `# Generated by safeword
version: "2"

linters:
  default: all
  exclusions:
    presets:
      - std-error-handling    # if err != nil patterns
      - common-false-positives
  settings:
    nestif:
      min-complexity: 4       # Match ESLint max-depth
    funlen:
      lines: 60
      statements: 40
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Deprecated: use io and os packages"

formatters:
  enable:
    - gofumpt
`;
}

/**
 * Set up Go tooling configuration.
 *
 * Creates .golangci.yml if it doesn't exist.
 * Respects existing configuration (won't overwrite).
 *
 * @param cwd - Project root directory
 * @returns Result with created files
 */
export function setupGoTooling(cwd: string): SetupResult {
  const result: SetupResult = { files: [] };

  const configPath = nodePath.join(cwd, '.golangci.yml');

  // Skip if config already exists (don't clobber)
  if (exists(configPath)) {
    return result;
  }

  // Generate golangci-lint config
  const config = generateGolangciConfig();
  writeFile(configPath, config);
  result.files.push('.golangci.yml');

  return result;
}
