/**
 * Go-specific Setup Utilities
 *
 * Provides config generation for golangci-lint.
 * File creation is handled by the schema system (managedFiles).
 *
 * Future: Layer detection for depguard import rules.
 */

import type { SetupResult } from '../types.js';

/**
 * Generate golangci-lint v2 configuration.
 *
 * Uses ALL linters for maximum strictness, matching our philosophy
 * for TypeScript (ESLint) and Python (ruff).
 *
 * Key constraints (via included linters):
 * - cyclop: max-complexity 10 (default)
 * - nestif: min-complexity 4 (matches ESLint max-depth)
 * - funlen: 60 lines, 40 statements (defaults)
 */
export function generateGolangciConfig(): string {
  return `# Generated by safeword - DO NOT EDIT
# To customize, add overrides below the formatters section

version: "2"

linters:
  default: all
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
  settings:
    nestif:
      min-complexity: 4

formatters:
  enable:
    - gofumpt
`;
}

/**
 * Set up Go tooling configuration.
 *
 * Note: .golangci.yml is now created by the schema system (managedFiles).
 * This function exists for future Go-specific setup (layer detection).
 *
 * @returns Empty result (schema handles file creation)
 */
export function setupGoTooling(): SetupResult {
  // .golangci.yml is created by schema.ts managedFiles
  // Future: Add layer detection for depguard rules here
  return { files: [] };
}
