/**
 * TOML Section Merging Utilities
 *
 * Line-based TOML manipulation without external dependencies.
 * Used for adding sections to pyproject.toml (Ruff, import-linter).
 *
 * @see ARCHITECTURE.md → "TOML Parsing Without Dependencies"
 */

// ============================================================================
// Shared Ruff Configuration
// ============================================================================

/**
 * Shared Ruff lint rules for .safeword/ruff.toml.
 * Used by both standalone and extending configs.
 */
const RUFF_LINT_RULES = `[lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstyle - too noisy for LLM code
    "ANN",    # flake8-annotations - mypy handles this
    "COM812", # missing trailing comma - conflicts with formatter
    "ISC001", # single-line-implicit-string-concatenation - conflicts with formatter
    "E501",   # line too long - formatter handles this
]

[lint.per-file-ignores]
"tests/**" = ["S101"]  # allow assert in tests

[lint.mccabe]
max-complexity = 10`;

/**
 * Check if a TOML section header exists in the content.
 * @param content - TOML file content
 * @param section - Section header (e.g., '[tool.ruff]')
 */
export function hasTomlSection(content: string, section: string): boolean {
  // Match exact section header at start of line
  // Section comes from our own templates (e.g., '[tool.ruff]'), properly escaped
  const escapedSection = section.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);
  // eslint-disable-next-line security/detect-non-literal-regexp -- Input is trusted and escaped
  const regex = new RegExp(String.raw`^${escapedSection}\s*$`, 'm');
  return regex.test(content);
}

/**
 * Append a TOML section to the end of a file.
 * Does NOT overwrite if section already exists.
 *
 * @param content - Existing TOML file content
 * @param section - Section to add (including header and content)
 * @returns Updated content, or original if section exists
 */
export function appendTomlSection(content: string, section: string): string {
  // Extract the section header from the section content (first line starting with [)
  const headerMatch = /^\[.+\]/m.exec(section);
  if (!headerMatch) return content;

  const header = headerMatch[0];

  // Don't add if section already exists
  if (hasTomlSection(content, header)) {
    return content;
  }

  // Ensure content ends with newline, then add blank line and new section
  const trimmedContent = content.trimEnd();
  return `${trimmedContent}\n\n${section.trim()}\n`;
}

/**
 * Generate Ruff configuration for .safeword/ruff.toml.
 *
 * If project has existing [tool.ruff] config, extends it with stricter rules.
 * Otherwise generates standalone config.
 *
 * Uses ALL rules for maximum strictness, matching ESLint/golangci-lint philosophy.
 * Ignores noisy rules that conflict with formatters or are redundant with mypy.
 *
 * This file is managed by safeword and updated on upgrade.
 *
 * @param existingRuffConfig - True if project has [tool.ruff] in pyproject.toml
 */
export function generateRuffBaseConfig(existingRuffConfig = false): string {
  if (existingRuffConfig) {
    // Extend project's existing Ruff config with safeword's stricter rules
    return `# Safeword Ruff config - extends project config with stricter rules
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# Re-run \`safeword upgrade\` to regenerate after project config changes.

# Inherit from project's pyproject.toml [tool.ruff] section
extend = "../pyproject.toml"

# Safeword overrides (stricter than project defaults)
# These rules take precedence over project config
line-length = 100

${RUFF_LINT_RULES}
`;
  }

  // Standalone config (no project config to extend)
  return `# Generated by safeword - DO NOT EDIT
# Customize in pyproject.toml [tool.ruff] section

line-length = 100

${RUFF_LINT_RULES}
`;
}

/**
 * Generate minimal Ruff extend reference for pyproject.toml.
 *
 * Points to .safeword/ruff.toml where actual rules live.
 * User can add overrides in this section.
 */
export function generateRuffConfig(): string {
  return `[tool.ruff]
extend = ".safeword/ruff.toml"`;
}

/**
 * Generate import-linter configuration for pyproject.toml.
 *
 * @param layers - Detected layers (e.g., ['domain', 'services', 'api'])
 * @param rootPackage - Root package name for the project
 */
export function generateImportLinterConfig(layers: string[], rootPackage: string): string {
  if (layers.length < 2) return '';

  const layerList = layers.map(l => `    "${rootPackage}.${l}"`).join(',\n');

  return `[tool.importlinter]
root_packages = ["${rootPackage}"]

[tool.importlinter.contracts.layers]
name = "Layer architecture"
type = "layers"
layers = [
${layerList}
]`;
}

/**
 * Generate mypy configuration section for pyproject.toml.
 * Minimal config to make mypy usable without being too strict.
 */
export function generateMypyConfig(): string {
  return `[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
pretty = true`;
}
